### PR TITLE
apiextentions V1

### PR DESCRIPTION
**Pull request by k0da**

### CODE REVIEW

**Review by ytsarev — DISMISSED** [review]

**Review by ytsarev — COMMENTED** [review]
lgtm, some tests are failing though

**Comment by k0da** [comment]
@ytsarev tests are fixed now

**Comment by k0da** [comment]
@somaritane @kuritka any opinion on this?

**Review by ytsarev — APPROVED** [review]

**Review by somaritane — APPROVED** [review]
lgtm

**Pull request merged**
